version: '3.7'

services:
  jenkins:
    build: .
    container_name: jenkins
    restart: unless-stopped
    ports:
      - "8085:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    environment:
      JAVA_OPTS: "-Xmx512m -Xms256m"
    mem_limit: 1g
    cpus: 0.75

volumes:
  jenkins_home:
